### ISSUE TITLE
Edits to site as requested by Carter

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/mavc-theme#18]
Email from Carter on 2 September 2015:
## UK related contents should be removed from instance:
- [x] Holidays
- [x] A banner usually shows up about WhatDoTheyKnow at the top of the page when browsing the instance
## Footer:
- [x] The Liberian seal should be resized to the size of the IIC logo. (PR: #20)
- [x] It should also be moved to the far left corner of the footer so it appears on the left of the page and IIC on the right in the footer. (PR: #20)
## Menu Bar:
- [ ] ~~Add all new pages to the menu bar~~ (https://github.com/mysociety/mavc-theme/issues/16)
- [ ] ~~Place the help menu in the far right corner of the page and use the  question mark icon (?) instead of the word help, since it's not a regular page for the instance transactions.~~ (#21)

**Comment by garethrees** [comment]
All outstanding issues covered in independent tickets
